# -- Theme Options --
colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# This looks for your engineering work in the projects folder
mainSections = ["projects", "posts"]

[header]
  layout = "fixed"

[footer]
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[appearance]
  theme = "dark"
  enableApperanceEffects = true

[homepage]
  layout = "background"
  homepageImage = "img/hero-bg.jpg"
  canvas = true
  showRecent = true
  showRecentItems = 6
  cardView = true
  layoutBackgroundBlur = true

[canvas]
  enable = true
  duration = 20
  speed = 10
  color = "primary"

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = true
  showTableOfContents = true
  showWordCount = true
  showSummary = true
  sharingLinks = ["linkedin", "twitter", "whatsapp"]

[list]
  showSummary = true
  groupByYear = true
  cardView = true
  constrainItemsWidth = true

[taxonomy]
  showTermCount = true
